version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn rest start &
            - run: sleep 10
            - run: curl http://localhost:9000/plants
            # - run: wget --retry-connrefused --waitretry=1 --read-timeout=60 --timeout=55 -t 55 http://localhost:9000/plants
            - run: yarn rest test:newman
workflows:
  build-and-test:
    jobs:
      - build-and-test
      # TODO: Add a real build step
      # Use a "production start" for testing the REST API
