name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test



# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   rest-build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: yarn install
#             - run: yarn test
#             - run:
#                 command: yarn rest start
#                 background: true
#             - run:
#                 shell: /bin/sh
#                 command: |
#                   wget --retry-connrefused --waitretry=1 --read-timeout=60 --timeout=55 -t 55 http://localhost:9000/plants
#                   :
#             - run: yarn rest test:newman
# workflows:
#   rest-build-and-test:
#     jobs:
#       - rest-build-and-test
#       # TODO: Add a real build step
#       # Use a "production start" for testing the REST API
